#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
import argparse
from pathlib import Path
from scripts import utils, files, config


def run(args):
    """
    Main frontend for demultiplexing and QA/QC
    """
    runs = files.get_run_directories(args.rundir, seq_dir=args.seq_dir)
    exec_config = config.base_config(qc=args.noqc)
 
    for (rundir, run_infos) in runs:
        sample_sheet = run_infos['samplesheet']
        sample_list = [
            dict(sid=sample.Sample_ID+'_S'+str(i), r1_adapter=sample.index, r2_adapter=sample.index2) 
            for i, sample in enumerate(sample_sheet.samples, start=1)
        ]
        project_list = list(set([_sample.Sample_Project for _sample in sample_sheet.samples]))
        # TODO: enforce single project
        assert len(project_list) == 1

        pairs = ['1', '2'] if sample_sheet.is_paired_end else ['1']

        # ~~~ general run configuration ~~~
        exec_config['run_ids'].append(rundir.name)
        exec_config['demux_input_dir'].append(rundir.resolve())
        exec_config['sids'].append([x['sid'] for x in sample_list])
        exec_config['project'].append(project_list[0])
        exec_config['rnums'].append(pairs)

        # ~~~ demultiplexing configuration ~~~
        exec_config['bcl_files'].append([x for x in Path(rundir).rglob('*.bcl.*') if not 'tmp' in str(x)])

        # ~~~ QC/QA configuration ~~~
        sample_sheet = run_infos['samplesheet']
        exec_config['sample_sheet'].append(str(sample_sheet.path.absolute()))
        exec_config['samples'].append(sample_list)
        
        # ~~~ output verification ~~~
        files.valid_run_output(args.output, dry_run=args.dry_run)
        exec_config['out_to'].append(str(Path(args.output).absolute()))

    utils.exec_pipeline(exec_config, dry_run=args.dry_run, local=args.local)


if __name__ == '__main__':
    main_parser = argparse.ArgumentParser(prog='weave')
    sub_parsers = main_parser.add_subparsers(help='run subcommand help')

    # ~~~ run subcommand ~~~
    parser_run = sub_parsers.add_parser('run')
    parser_run.add_argument('rundir', metavar='<run directory>', nargs="+", type=utils.valid_run_input, 
                            help='Full & complete run id (format YYMMDD_INSTRUMENTID_TIME_FLOWCELLID) or absolute paths')
    parser_run.add_argument('-s', '--seq_dir', metavar='<sequencing directory>', default=None, type=str,
                            help='Root directory for sequencing data (defaults for biowulf/bigsky/locus), must contain directories ' + \
                            'matching run ids, if not using full paths.')
    parser_run.add_argument('-o', '--output', metavar='<output directory>', default=None, type=str, 
                            help='Top-level output directory for demultiplexing data (defaults to input directory + runid + "_demux")')
    parser_run.add_argument('-d', '--dry-run', action='store_true',
                            help='Dry run the demultiplexing workflow')
    parser_run.add_argument('-n', '--noqc', action='store_false',
                            help='Dry run the demultiplexing workflow')
    parser_run.add_argument('-l', '--local', action='store_true',
                            help='Execute pipeline locally without a dispatching executor')

    parser_run.set_defaults(func = run)
    args = main_parser.parse_args()
    args.func(args)