import os
from sample_sheet import SampleSheet
        
envvars: "SNK_CONFIG"
configfile: os.environ['SNK_CONFIG']
ruleorder:
    fastqc_untrimmed > index_annotations > trim_w_fastp > fastq_screen

rule all:
    input:
        # fastqc on untrimmed reads
        expand("{qc_dir}/{sids}_R{rnum}_untrimmed_fastqc.zip", qc_dir=config['untrimmed_qc_dir'], sids=config['sids'], rnum=config['rnums']),
        # fastqc on trimmed reads
        expand("{qc_dir}/{sids}_trimmed_fastqc.zip", qc_dir=config['trimmed_qc_dir'], sids=config['sids']),
        # fastp trimming metrics
        expand("{trim_dir}/{sids}.html", trim_dir=config['trim_dir'], sids=config['sids']),
        # fastq screen
        expand("{trim_qc_dir}/fastq_screen/{sids}.fastq_screen.txt", trim_qc_dir=config['trimmed_qc_dir'], sids=config['sids']),
        expand("{trim_qc_dir}/fastq_screen/{sids}.fastq_screen.png", trim_qc_dir=config['trimmed_qc_dir'], sids=config['sids']),
        

include: "fastq.smk"
include: "qc.smk"