import os
from sample_sheet import SampleSheet
        
envvars: "SNK_CONFIG"
configfile: os.environ['SNK_CONFIG']

ruleorder:
    fastqc_untrimmed > index_annotations > trim_w_fastp > fastq_screen

rule all:
    input:
        # fastqc on untrimmed reads
        expand("{qc_dir}/{project}/{sids}_R{rnum}_001_fastqc.zip", qc_dir=config['untrimmed_qc_dir'], 
               project=config['projects'], sids=config['sids'], rnum=config['rnums']),
        # fastqc on trimmed reads
        expand("{qc_dir}/{project}/{sids}_trimmed_R{rnum}_fastqc.zip", qc_dir=config['trimmed_qc_dir'], 
               sids=config['sids'], project=config['projects'], rnum=config['rnums']),
        # fastp trimming metrics
        expand("{trim_dir}/{project}/{sids}_trimmed_R{rnum}.fastq.gz", trim_dir=config['trim_dir'], sids=config['sids'],
               project=config['projects'], rnum=config['rnums']),
        # fastq screen
        expand("{trim_qc_dir}/fastq_screen/{sids}_{project}/{sids}_trimmed_R{rnum}_screen.html", trim_qc_dir=config['trimmed_qc_dir'], 
               sids=config['sids'], rnum=config['rnums'], project=config['projects']),


include: "fastq.smk"
include: "qc.smk"