
import os


configfile: os.environ['SMK_CONFIG']


rule bcl2fastq:
	input:
		expand("{run}", run=config['runs']),
		expand("{run}/SampleSheet.csv", run=config['runs'])
	output:
		seq_data 	= expand(
						"{run}/{project}/{sids}_S{snum}_R{rnum}.fastq.gz", 
						run=config['runs'], 
						project=config['projects'], 
						sids=config['sample_ids'],
					  )
		reports 	= expand("{run}/Reports", run=config['runs'])
		stats		= expand("{run}/Stats", run=config['runs'])
	singularity: "docker://umccr/bcl2fastq"
	shell: 
		"""
			bcl2fastq \ 
			--runfolder-dir {input.run_dirs} \
			--min-log-level=INFO \
			-r {threads} -p {threads} -w {threads} \
			--no-lane-splitting
		"""