
import os


configfile: os.environ['SMK_CONFIG']

demux_runs_projects = {
	'run': config['runs'],
	'project': config['projects'],
}


demux_full_params = {
	**demux_runs_projects,
	'sids': config['sids'], 
	'snum': config['snums'], 
	'rnum': config['rnums']
}


rule all:
	input:
		expand("{run}", run=config['runs']),
		expand("{run}/{project}/{sids}_S{snum}_R{rnum}.fastq.gz", **demux_full_params),


rule bcl2fastq:
	input:
		run_dirs 		  	= expand("{run}", run=config['runs']),
		binary_base_calls	= expand("{files}", files=config['bcl_files']),
		samplesheets 	  	= expand("{run}/SampleSheet.csv", run=config['runs'])
	output:
		seq_data 			= expand("{run}/{project}/{sids}_S{snum}_R{rnum}.fastq.gz", **demux_full_params),
		reports 			= expand("{run}/{project}/Reports", **demux_runs_projects),
		stats				= expand("{run}/{project}/Stats", **demux_runs_projects)
	params:
		out_dir			  	= expand("{run}/{project}", **demux_runs_projects),
	singularity: "docker://umccr/bcl2fastq"
	threads: 24
	shell: 
		r"""
			bcl2fastq \
			--runfolder-dir {input.run_dirs} \
			--min-log-level=INFO \
			-r {threads} -p {threads} -w {threads} \
			--no-lane-splitting -o {params.out_dir}
		"""